---
title: "R Notebook"
output: html_notebook
---

```{r}
library(plotly)

df <- read.csv("meninas.csv", stringsAsFactors=FALSE, sep=",")
df_bin <- read.csv("make_binary/meninasbin.csv", stringsAsFactors=FALSE, sep=";")
```

```{r}
str(df)
```

```{r}
library(cdparcoord)
df_aux = df %>%
  select(Course, Option, Min.Graduation.Credits, UF.birth)
df_aux <- makeFactor(df_aux,c('Min.Graduation.Credits'))
#df_aux <- makeFactor(df_aux,c('Período.de.saída.da.opção','Periodo.de.Ingresso.na.Unb','Periodo.de.ingresso.na.opção'))
#pe25disc <- discretize(df_aux,nlevels=5)  
discparcoord(df_aux,k=1000)
```


```{r}
library(cdparcoord)
df_aux = df %>%
  select(Leaving.option.period, Leaving.option.form)
  #filter((Leaving.option.period >= 19920 & Leaving.option.period < 19951) | (Leaving.option.period > 20010 & Leaving.option.period < 20161))
df_aux <- makeFactor(df_aux,c('Leaving.option.period'))
#df_aux <- makeFactor(df_aux,c('Período.de.saída.da.opção','Periodo.de.Ingresso.na.Unb','Periodo.de.ingresso.na.opção'))
#pe25disc <- discretize(df_aux,nlevels=5)  
discparcoord(df_aux,k=1000)
```



```{r}
library(cdparcoord)
df_aux = df %>%
  select(Leaving.option.period, Leaving.option.form, Entrance.UnB.period, Entrance.option.period)
df_aux <- makeFactor(df_aux,c('Leaving.option.period', 'Entrance.UnB.period', 'Entrance.option.period'))
#df_aux <- makeFactor(df_aux,c('Leaving.option.period','Entrance.UnB.period','Entrance.option.period'))
#pe25disc <- discretize(df_aux,nlevels=5)  
discparcoord(df_aux,k=1000)
```



```{r}
library(cdparcoord)
df_aux = df %>%
  select(School.type, Entrance.option.period, Quota, Race)
df_aux <- makeFactor(df_aux,c('Entrance.option.period'))
#pe25disc <- discretize(df_aux,nlevels=5)  
discparcoord(df_aux,k=1000)
```

```{r}
library(cdparcoord)
df_aux = df %>%
  select(Entrance.option.form, Total.Credits, Paid.in.credits)
#df_aux <- makeFactor(df_aux,c('Créditos.integralizados.no.total', 'Créditos.cursados.no.total'))
#pe25disc <- discretize(df_aux,nlevels=5)  
discparcoord(df_aux,k=1000)
```

